spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/routing
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Tes666ter
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: never
  thymeleaf:
    cache: false